# Shared steps to set up the Emacs environment for CI.
---
name: Setup dev environment
description: Installs Emacs, Eask, Eask dependencies, and other npm packages
runs:
  using: composite
  steps:
    # Eask dependencies are installed via an npm postinstall hook, so Emacs needs to be installed
    # first.
    - name: Setup Emacs
      uses: purcell/setup-emacs@v6.0
      with:
        version: 30.1

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "lts/*"
        cache: npm

    - name: Install npm dependencies
      run: npm ci
      shell: bash
