FROM node:24-alpine3.23
RUN apk add bash emacs-nox git grep make patch python3

WORKDIR /opt/macher-deps
COPY package.json package-lock.json ./
RUN npm ci --ignore-scripts

ENV PATH="/opt/macher-deps/node_modules/.bin:${PATH}"
